import type { AssemblyStory } from './assemblyStories'

// Authored step stories for the foundations recipes. Steps follow each recipe's tool order.
// 'fit' links are pairs recorded in pairsWellWith; 'recipe' links describe how this recipe combines two parts,
// which is an integration to design, not an automatic connection. 'tension' links appear only in cautionary recipes.
export const foundationsStories: Record<string, AssemblyStory> = {
  'starter-app': {
    recipeId: 'starter-app',
    steps: [
      { toolId: 'nextjs', action: 'Build the front end', explanation: 'Start with the pages people use; Next.js server code can hold early back-end logic, but decide where that line sits.' },
      { toolId: 'nodejs', action: 'Run the server side', explanation: 'Next.js runs on Node.js, so one language covers the front end and the first API routes.' },
      { toolId: 'postgresql', action: 'Store the data', explanation: 'Keep application state in PostgreSQL, not in the process, so the app can restart without losing it.' },
      { toolId: 'heroku', action: 'Put it somewhere managed', explanation: 'Heroku builds and runs the app from source, so there are no servers to manage; the team still owns the app\'s config and data.' },
    ],
    links: [
      { first: 'nextjs', second: 'nodejs', kind: 'fit', note: 'Next.js requires Node.js; the documented minimum at the time of review was 20.9.' },
      { first: 'nodejs', second: 'postgresql', kind: 'fit', note: 'Node.js connects through a client library such as node-postgres; the driver and schema migrations are choices the team makes.' },
      { first: 'nodejs', second: 'heroku', kind: 'fit', note: 'Heroku maintains an official Node.js buildpack.' },
      { first: 'postgresql', second: 'heroku', kind: 'fit', note: 'Heroku Postgres is a managed PostgreSQL add-on; restores still need testing.' },
      { first: 'nextjs', second: 'heroku', kind: 'recipe', note: 'The recipe deploys the Next.js app through the Node.js buildpack; build and start commands are app configuration.' },
    ],
  },
  'authenticated-app': {
    recipeId: 'authenticated-app',
    steps: [
      { toolId: 'nextjs', action: 'Build the front end', explanation: 'The same Next.js front end as the starter app, now with pages only logged-in users should see.' },
      { toolId: 'nodejs', action: 'Run the server side', explanation: 'Node.js runs the server code that will check each request\'s session.' },
      { toolId: 'postgresql', action: 'Store the data', explanation: 'Application data stays in PostgreSQL; user records may now link to identities held by Auth0.' },
      { toolId: 'heroku', action: 'Keep it managed', explanation: 'Heroku still runs the app; keep Auth0 credentials in config vars rather than in the repository.' },
      { toolId: 'auth0', action: 'Add login', explanation: 'Auth0 handles sign-in so the team does not store passwords, but what each user may do is still application code.' },
      { toolId: 'github-actions', action: 'Test before shipping', explanation: 'A workflow runs tests on every pull request, so changes are checked before they are merged.' },
    ],
    links: [
      { first: 'nextjs', second: 'nodejs', kind: 'fit', note: 'Next.js requires Node.js.' },
      { first: 'nodejs', second: 'postgresql', kind: 'fit', note: 'Node.js connects through a client library such as node-postgres.' },
      { first: 'nodejs', second: 'heroku', kind: 'fit', note: 'Heroku maintains an official Node.js buildpack.' },
      { first: 'postgresql', second: 'heroku', kind: 'fit', note: 'Heroku Postgres is a managed PostgreSQL add-on.' },
      { first: 'nextjs', second: 'auth0', kind: 'fit', note: 'Auth0 publishes a Next.js SDK.' },
      { first: 'nodejs', second: 'auth0', kind: 'fit', note: 'Auth0 publishes express-openid-connect for Express on Node.js.' },
      { first: 'github-actions', second: 'heroku', kind: 'recipe', note: 'The recipe ships passing builds to Heroku; whether a workflow step or Heroku\'s GitHub integration does the deploy is a choice to make.' },
    ],
  },
  'watched-app': {
    recipeId: 'watched-app',
    steps: [
      { toolId: 'nextjs', action: 'Build the front end', explanation: 'The same Next.js front end, whose server code can now emit telemetry.' },
      { toolId: 'nodejs', action: 'Run the server side', explanation: 'Node.js runs the back end that users\' requests depend on.' },
      { toolId: 'postgresql', action: 'Store the data', explanation: 'PostgreSQL holds application state; slow queries will show up in traces once instrumented.' },
      { toolId: 'heroku', action: 'Keep it managed', explanation: 'Heroku runs the app; its own logs and metrics do not replace application telemetry.' },
      { toolId: 'auth0', action: 'Keep login hosted', explanation: 'Auth0 handles sign-in; login failures are worth watching as closely as server errors.' },
      { toolId: 'github-actions', action: 'Test before shipping', explanation: 'CI checks each change, and telemetry will show whether a release that passed CI behaves in production.' },
      { toolId: 'opentelemetry', action: 'Instrument the app', explanation: 'Emit traces and metrics from Next.js and Node.js, and choose a backend to send them to, which this recipe leaves open.' },
      { toolId: 'pagerduty', action: 'Page a person', explanation: 'Route alerts to whoever is on call, once a backend turns telemetry into alerts worth waking someone for.' },
    ],
    links: [
      { first: 'nextjs', second: 'nodejs', kind: 'fit', note: 'Next.js requires Node.js.' },
      { first: 'nodejs', second: 'postgresql', kind: 'fit', note: 'Node.js connects through a client library such as node-postgres.' },
      { first: 'nodejs', second: 'heroku', kind: 'fit', note: 'Heroku maintains an official Node.js buildpack.' },
      { first: 'postgresql', second: 'heroku', kind: 'fit', note: 'Heroku Postgres is a managed PostgreSQL add-on.' },
      { first: 'nextjs', second: 'auth0', kind: 'fit', note: 'Auth0 publishes a Next.js SDK.' },
      { first: 'nodejs', second: 'auth0', kind: 'fit', note: 'Auth0 publishes express-openid-connect for Express on Node.js.' },
      { first: 'nextjs', second: 'opentelemetry', kind: 'fit', note: 'Next.js documents OpenTelemetry instrumentation.' },
      { first: 'nodejs', second: 'opentelemetry', kind: 'fit', note: 'The OpenTelemetry JavaScript SDK offers Node.js auto-instrumentation.' },
      { first: 'opentelemetry', second: 'pagerduty', kind: 'recipe', note: 'No direct connection: a telemetry backend with alert rules has to sit between them before anything pages.' },
    ],
  },
  'container-service': {
    recipeId: 'container-service',
    steps: [
      { toolId: 'django', action: 'Write the service', explanation: 'Django supplies the ORM, migrations, and admin, so the service starts with many decisions already made.' },
      { toolId: 'postgresql', action: 'Attach the database', explanation: 'PostgreSQL is an officially supported Django database; the connection comes from the environment, not the code.' },
      { toolId: 'redis', action: 'Add a cache', explanation: 'Use Django\'s built-in Redis cache backend, and treat the cache as something that can be lost.' },
      { toolId: 'docker', action: 'Package it', explanation: 'Build the service into an image, keeping secrets out of the layers.' },
      { toolId: 'harbor', action: 'Store the image', explanation: 'Push images to a private Harbor registry with access control, which the team now has to run.' },
      { toolId: 'github-actions', action: 'Build in CI', explanation: 'A workflow builds, tests, and pushes the image on each change, with third-party actions pinned to commit SHAs.' },
      { toolId: 'trivy', action: 'Scan what ships', explanation: 'Scan the image and generate an SBOM before it is pushed; someone still decides which findings block a release.' },
      { toolId: 'terraform', action: 'Describe the infrastructure', explanation: 'Keep the infrastructure in reviewed configuration, and store state where secrets in it are protected.' },
    ],
    links: [
      { first: 'django', second: 'postgresql', kind: 'fit', note: 'Django officially supports PostgreSQL.' },
      { first: 'django', second: 'redis', kind: 'fit', note: 'Django includes a Redis cache backend.' },
      { first: 'django', second: 'docker', kind: 'recipe', note: 'The recipe packages the Django service as an image; the Dockerfile and process command are the team\'s to write.' },
      { first: 'docker', second: 'harbor', kind: 'fit', note: 'Harbor is an OCI registry that accepts standard image pushes.' },
      { first: 'docker', second: 'github-actions', kind: 'fit', note: 'Docker publishes build-push-action for GitHub Actions.' },
      { first: 'github-actions', second: 'harbor', kind: 'fit', note: 'The workflow pushes images with a Harbor robot account, which Harbor provides for automation.' },
      { first: 'trivy', second: 'github-actions', kind: 'fit', note: 'trivy-action runs Trivy in workflows; pin it to a commit SHA after the March 2026 tag hijack.' },
      { first: 'trivy', second: 'docker', kind: 'fit', note: 'Trivy scans container images for known vulnerabilities and can produce an SBOM.' },
      { first: 'trivy', second: 'harbor', kind: 'fit', note: 'Harbor uses Trivy for image scanning when enabled at install.' },
      { first: 'trivy', second: 'terraform', kind: 'fit', note: 'Trivy can scan Terraform plans for misconfigurations.' },
      { first: 'terraform', second: 'github-actions', kind: 'fit', note: 'hashicorp/setup-terraform runs Terraform in workflows.' },
    ],
  },
  'gitops-platform': {
    recipeId: 'gitops-platform',
    steps: [
      { toolId: 'kubernetes', action: 'Provide the cluster', explanation: 'Kubernetes schedules and restarts containers for several teams, and brings real operating load with it.' },
      { toolId: 'argocd', action: 'Deploy from Git', explanation: 'Argo CD keeps the cluster in sync with manifests in Git and reports drift; it does not build or test anything.' },
      { toolId: 'harbor', action: 'Serve the images', explanation: 'Harbor gives the cluster one scanned, access-controlled registry to pull from.' },
      { toolId: 'terraform', action: 'Codify the platform', explanation: 'Terraform describes the clusters and supporting services, so the platform can be rebuilt and reviewed.' },
      { toolId: 'prometheus', action: 'Collect metrics', explanation: 'Prometheus scrapes cluster, Argo CD, and application metrics and evaluates alert rules.' },
      { toolId: 'grafana', action: 'Show the state', explanation: 'Grafana dashboards make the metrics readable; alert rules and owners matter more than panel count.' },
      { toolId: 'pagerduty', action: 'Page a person', explanation: 'Alerts from Alertmanager or Grafana reach whoever is on call, with escalation if nobody answers.' },
      { toolId: 'vault', action: 'Keep secrets out of Git', explanation: 'Vault syncs secrets into the cluster through its operator, so the Git repository holds references, not values.' },
    ],
    links: [
      { first: 'kubernetes', second: 'argocd', kind: 'fit', note: 'Argo CD is GitOps continuous delivery built for Kubernetes.' },
      { first: 'harbor', second: 'kubernetes', kind: 'fit', note: 'Clusters pull images from Harbor like any OCI registry; pull credentials still need managing.' },
      { first: 'argocd', second: 'harbor', kind: 'recipe', note: 'The recipe has manifests in Git reference images in Harbor; Argo CD can also use OCI artifacts as an application source.' },
      { first: 'terraform', second: 'kubernetes', kind: 'fit', note: 'A Terraform Kubernetes provider exists; cluster creation uses the cloud provider\'s own Terraform provider.' },
      { first: 'prometheus', second: 'kubernetes', kind: 'fit', note: 'Kubernetes components emit metrics in Prometheus format.' },
      { first: 'prometheus', second: 'argocd', kind: 'fit', note: 'Argo CD exposes Prometheus metrics about applications and syncs.' },
      { first: 'prometheus', second: 'grafana', kind: 'fit', note: 'Grafana has a Prometheus data source.' },
      { first: 'prometheus', second: 'pagerduty', kind: 'fit', note: 'Alertmanager has a PagerDuty receiver.' },
      { first: 'grafana', second: 'pagerduty', kind: 'fit', note: 'Grafana Alerting documents a PagerDuty contact point.' },
      { first: 'terraform', second: 'grafana', kind: 'fit', note: 'The Grafana Terraform provider manages dashboards and alerts as code.' },
      { first: 'terraform', second: 'pagerduty', kind: 'fit', note: 'The PagerDuty Terraform provider manages services and schedules as code.' },
      { first: 'vault', second: 'kubernetes', kind: 'fit', note: 'The Vault Secrets Operator syncs Vault secrets into Kubernetes Secrets.' },
      { first: 'vault', second: 'terraform', kind: 'fit', note: 'A Terraform provider manages Vault; avoid writing secret values into Terraform state.' },
    ],
  },
  'self-hosted-app': {
    recipeId: 'self-hosted-app',
    steps: [
      { toolId: 'nextjs', action: 'Build the front end', explanation: 'The same Next.js front end as a hosted app; nothing in it depends on where the machine sits.' },
      { toolId: 'nodejs', action: 'Run the server side', explanation: 'Node.js runs the server code, with configuration read from the environment so the app can move later.' },
      { toolId: 'postgresql', action: 'Store the data', explanation: 'PostgreSQL holds application state on the team\'s own disks, so backups that leave the machine and tested restores are now the team\'s job.' },
      { toolId: 'docker', action: 'Package it', explanation: 'Build the app into an image, so the machine runs a known build rather than a hand-installed copy.' },
      { toolId: 'self-hosted', action: 'Run it on your own hardware', explanation: 'A server or small machine the team owns runs the containers. Patching, power, network, and physical security come with it.' },
      { toolId: 'keycloak', action: 'Add login', explanation: 'Keycloak handles sign-in without a hosted vendor; if it is down, nobody logs in, and upgrading it is the team\'s work.' },
      { toolId: 'prometheus', action: 'Watch the machine', explanation: 'Prometheus scrapes node_exporter for disk, memory, and CPU, and evaluates alert rules. Application metrics need instrumentation first.' },
      { toolId: 'grafana', action: 'Show the state', explanation: 'Grafana dashboards make the metrics readable. If they run on the same machine, they go down with it, so watch it from somewhere else too.' },
    ],
    links: [
      { first: 'nextjs', second: 'nodejs', kind: 'fit', note: 'Next.js requires Node.js.' },
      { first: 'nodejs', second: 'postgresql', kind: 'fit', note: 'Node.js connects through a client library such as node-postgres.' },
      { first: 'nodejs', second: 'docker', kind: 'fit', note: 'There is an official Node.js Docker image.' },
      { first: 'docker', second: 'self-hosted', kind: 'fit', note: 'Docker Engine installs on the team\'s own Linux servers; on macOS the documented path is Docker Desktop, with its own licence terms.' },
      { first: 'postgresql', second: 'self-hosted', kind: 'recipe', note: 'The recipe keeps the database on the team\'s own hardware; backups, upgrades, and restores have no managed service behind them.' },
      { first: 'keycloak', second: 'postgresql', kind: 'fit', note: 'Keycloak can use PostgreSQL as its database; keep it separate from application data.' },
      { first: 'nextjs', second: 'keycloak', kind: 'recipe', note: 'The recipe logs users in through Keycloak over OpenID Connect; the client configuration and session handling are application work.' },
      { first: 'prometheus', second: 'self-hosted', kind: 'fit', note: 'The official node_exporter exposes the host\'s hardware and OS metrics to Prometheus.' },
      { first: 'nodejs', second: 'prometheus', kind: 'recipe', note: 'The recipe watches the service with Prometheus, but Node.js exposes no Prometheus metrics until it is instrumented.' },
      { first: 'prometheus', second: 'grafana', kind: 'fit', note: 'Grafana has a Prometheus data source.' },
      { first: 'grafana', second: 'keycloak', kind: 'fit', note: 'Grafana documents Keycloak login.' },
    ],
  },
  'platform-before-product': {
    recipeId: 'platform-before-product',
    steps: [
      { toolId: 'nodejs', action: 'Write one service', explanation: 'There is a single Node.js service, with no tests run in CI and no telemetry.' },
      { toolId: 'kubernetes', action: 'Stand up a cluster', explanation: 'A cluster built for many services now runs one, and its upkeep competes with product work.' },
      { toolId: 'argocd', action: 'Add GitOps', explanation: 'Argo CD deploys whatever reaches Git, and with no CI upstream, Git is the only gate.' },
      { toolId: 'terraform', action: 'Codify the platform', explanation: 'Infrastructure as code is sound on its own, but here it codifies a platform the product does not yet need.' },
    ],
    links: [
      { first: 'nodejs', second: 'kubernetes', kind: 'tension', note: 'In this design one service carries the operating load of a whole cluster, before a second service exists to share it.' },
      { first: 'nodejs', second: 'argocd', kind: 'tension', note: 'In this design GitOps deploys the service with no CI and no telemetry, so untested changes reach production and nobody sees the result.' },
      { first: 'kubernetes', second: 'argocd', kind: 'fit', note: 'The pairing itself is sound. The caution comes from when it was built, not from the two parts.' },
      { first: 'terraform', second: 'kubernetes', kind: 'fit', note: 'A Terraform Kubernetes provider exists; the pairing is sound, only premature here.' },
    ],
  },
}
